version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    privileged: true
    user: "0:0"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /Users/ofirzvishaboo/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "1"

  agent:
    image: agent:latest
    container_name: agent
    privileged: true
    user: "0:0"
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    volumes:
      - /Users/ofirzvishaboo/jenkins_agent:/home
      - /var/run/docker.sock:/var/run/docker.sock
      
    group_add:
      - "1"

volumes:
  jenkins_home: